#!/usr/bin/env bash
#
set -e

#
#	Prepare Airflow database
#
psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" <<-EOSQL
  CREATE USER ${AIRFLOWDB_USER} WITH PASSWORD '${AIRFLOWDB_PASSWORD}';
  CREATE DATABASE ${AIRFLOWDB_NAME};
  GRANT ALL PRIVILEGES ON DATABASE ${AIRFLOWDB_NAME} TO ${AIRFLOWDB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" -d "${AIRFLOWDB_NAME}" <<-EOSQL
   GRANT ALL ON SCHEMA public TO ${AIRFLOWDB_USER};
EOSQL

#
#	prepare dwh database
#
psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" <<-EOSQL
  CREATE USER ${DWHDB_USER} WITH PASSWORD '${DWHDB_PASSWORD}';
  CREATE DATABASE ${DWHDB_NAME};
  GRANT ALL PRIVILEGES ON DATABASE ${DWHDB_NAME} TO ${DWHDB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" -d "${DWHDB_NAME}" <<-EOSQL
   CREATE SCHEMA IF NOT EXISTS dwh_stage;
   CREATE SCHEMA IF NOT EXISTS dwh_core;
   CREATE SCHEMA IF NOT EXISTS dwh_access;

   GRANT ALL ON SCHEMA dwh_stage, dwh_core, dwh_access TO ${DWHDB_USER};
EOSQL
